[Applications/quick_ai] Link YOLOv11m in Meson build configuration
Added YOLOv11 to the models Meson configuration so that its source files are compiled on non-Android native platforms.
This resolves the 'undefined reference to vtable for quick_ai::Yolov11' linker error in the native build and guarantees CI compilation success.

Signed-off-by: SeungBaek Hong <sb92.hong@samsung.com>